<a href="https://colab.research.google.com/github/Jackson-Coulson/mis433/blob/main/Coulson_Jackson_assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [4]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? g
Welcome, g!


In [5]:
# complete your program here
f = int(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 12
12
12F is -11.11111111111111 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [6]:
# complete your program here

c = int(input('Please enter the temperature in Celcius: '))

print(c)

#Fahrenheit = (Celcius * 9/5) + 32
f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')
#print(str(c)+'C is '+str(f)+' in Fahrenheit. ')


Please enter the temperature in Celcius: 12
12
12C is 53.6 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [7]:
# complete your program here
d = int(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ')

if m.lower() == "f":

  #Celsius = (Fahrenheit – 32)*5/9
  c = (d - 32) * 5/9
  print(f'{d}F is {c} in Celsius. ')
  #print(str(f)+'F is '+str(c)+' in Celsius. ')
elif m.lower() == "c":

  #Fahrenheit = (Celcius * 9/5) + 32
  f = (d * 9/5) + 32
  print(f'{d}C is {f} in Fahrenheit. ')
  #print(str(c)+'C is '+str(f)+' in Fahrenheit. ')
else:
  print("Input invalid entry has to be either C or F")





Please enter the temperature: 12
Is this in Celsius or Fahrenheit? 12
Input invalid entry has to be either C or F


## Question 2

Have some fun with strings.

In [8]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [9]:
# Find the length of this sentence.
print(len(sentence))

48


In [10]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [11]:
# Extract a substring from the 10th character from left to the 10th character from right.
substring = sentence[9:-10]
print(substring)

heap. Show me the code - Linu


In [12]:
# Split the sentence into a list of substrings by space ' '.
listedsubstrings = sentence.split(" ")
print(listedsubstrings)


['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [13]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').

output = sentence.lower().replace(".", "").replace(" -", "").split(" ")
print(output)


['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [14]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
count = 0
#vowels = 'aeiou'
for v in vowels:
  if v in vowels:
    count += 1


print(count)

5


In [15]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
      print(f"Vowel is at index {i}")


Vowel is at index 1
Vowel is at index 5
Vowel is at index 10
Vowel is at index 11
Vowel is at index 17
Vowel is at index 21
Vowel is at index 25
Vowel is at index 28
Vowel is at index 30
Vowel is at index 35
Vowel is at index 37
Vowel is at index 41
Vowel is at index 44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [16]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for num in range(5):
  cubes.append(num ** 3)

print(cubes)


[0, 1, 8, 27, 64]


In [17]:
# Use list comprehension to create the same list

cubes = [num ** 3 for num in range(5)]
cubes

[0, 1, 8, 27, 64]

In [18]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowels = [i for i in range(len(sentence)) if sentence[i].lower() in "aeiou"]

print(vowels)


[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [19]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# add your code here
a = 0
b = 1

for i in range(n):
    fibonacci.append(a)

    next_num = a + b
    a = b
    b = next_num

print(fibonacci)



How many numbers do you want? 3
[0, 1, 1]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [20]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    "Pfizer": 0.95,
    "Moderna": 0.95,
    "AstraZeneca": 0.72,
    "Johnson & Johnson": 0.66}

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [22]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine

print(v_dict[v])

Which vaccine? Pfizer
0.95


In [24]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict["Sputnik V"] = 0.914

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [25]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary

v_dict["Sinovac"] = 0.5038

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [26]:
# Print vaccines with efficacy lower than 90%.
for i in v_dict.items():
  if i[1] < 0.90:
    print(i[0])

AstraZeneca
Johnson & Johnson
Sinovac


In [27]:
# delete the Sinovac vaccine from the dictionary.
del v_dict["Sinovac"]

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [29]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for i in sentence:
  if i != ' ':
    if i in ch_dict:
        ch_dict[i] += 1
    else:
      ch_dict[i] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [30]:
import numpy as np

In [44]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
print(np.array(np.arange(2, 41, 2)))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [45]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
print(np.array(np.arange(1, 40, 2)))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [46]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
print(np.arange(100).reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [48]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

print(M)

[[ 0.04932499  0.53282493  0.59321671 -0.72351965 -0.64002139  0.27728683
  -0.81908486  0.37887018  1.71674668  0.40962756]
 [ 0.89556396 -0.61996054  1.57978334  0.03318599  0.77555828 -1.2487179
  -1.61145531  1.01777972 -0.07466071  0.76480155]
 [-0.89444774 -1.10095858 -0.64277504 -1.09343353  0.6024698  -0.10532903
  -1.94342566  0.03359236 -0.72015087 -1.18218618]
 [-0.85834552 -1.19425258 -1.88175625 -0.65078466 -2.19042609  0.1735094
  -0.0787391   0.07218478 -0.38320156  0.25249969]
 [ 0.31541877  1.5636182  -0.36423907  0.99166684  0.71910308  1.54001078
  -0.35983537 -0.29678978 -0.50265039  0.35727155]
 [-2.74444371 -1.06475957  0.18279246 -0.16314331  0.20880416  1.07601536
   1.76360255 -1.00632289 -0.64615921 -0.63791865]
 [ 0.15604391 -1.4145008   0.2328627  -0.97393481 -0.80160519  0.43721471
  -1.04600336  0.05403758  0.34687952 -0.04434734]
 [-0.11389008  0.14268056 -0.24060914 -0.42490437 -1.01492787  2.70058088
  -0.29069223 -0.47774547  1.80602112  1.54891128]
 [

In [50]:
# Count the numbers in M with an absolute value greater than 1.
print(np.sum(np.abs(M) > 1))

33


In [51]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r,c))
print(arr)

Row count: 5
column count: 5
[[10 14 12 15 12]
 [11 11 15 16 13]
 [14 14 11 15 13]
 [17 14 14 14 11]
 [14 18 19 13 18]]


In [52]:
# output the element in the first row and the third column
print(arr[0, 2])

12


In [53]:
# output the element in the second row and the last column
print(arr[1, 4])

13


In [54]:
# output the second row of the array
print(arr[1])

[11 11 15 16 13]


In [55]:
# output the second last row of the array
print(arr[4])

[14 18 19 13 18]


In [56]:
# output the second column of the array
print(arr[:,1])

[14 11 14 14 18]


In [58]:
# output the second last column of the array
print(arr[:,3])

[15 16 15 14 13]


In [60]:
# output the upper-left 3x3 sub-array
print(arr[0:3,0:3])

[[10 14 12]
 [11 11 15]
 [14 14 11]]


In [62]:
# output the bottom-left 3x3 sub-array
print(arr[-3: , :3])

[[14 14 11]
 [17 14 14]
 [14 18 19]]


In [63]:
# output the upper-right 3x3 sub-array
print(arr[:3, 2:5])

[[12 15 12]
 [15 16 13]
 [11 15 13]]


In [65]:
# output the bottom-right 3x3 sub-array
print(arr[-3:, 2:5])

[[11 15 13]
 [14 14 11]
 [19 13 18]]


In [66]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
A = A.reshape(5,10)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [68]:
# add a row [51,...,60] to A
A = np.vstack((A, np.arange(51, 61)))
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [71]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:3, :]
A2 = A[3:, :]

print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [72]:
# Add 10 to each element of A
A = A +10

print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [73]:
# Calculate the square root of each element in A
A = np.sqrt(A)

print(A)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [77]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

print(M)

[[-1.10676201 -1.68602397 -0.83143879 -0.5460197  -0.18424468  0.02857849
  -0.95989771  0.09770083  0.41465311 -0.97845864]
 [-0.1534751   0.63593495 -1.9951729   0.81580336 -0.12976181 -0.10955763
  -0.02754062 -1.04922721 -0.67423069  0.14433414]
 [-0.1653627   1.12254246  1.49285002  0.08973204 -1.13496189 -0.57934385
   0.7704902  -0.6595481  -0.072972    0.18385515]
 [-1.13585207  0.12429827 -1.74304499 -0.50688916 -1.10813997 -0.50693314
   0.67217153 -0.28028985 -0.63862601  0.40248017]
 [-0.53485506  0.68309647 -0.49537045  0.41935766 -1.41207042  0.13562266
   0.02129663  0.04891103  0.63267963 -1.95051203]
 [-0.10040723 -0.96268504  0.81622465  0.07677302  0.56442038  0.24757453
  -0.59192585  0.09550128  0.71353458  2.10372262]
 [ 0.47052612 -0.26030633 -0.13688644 -1.40265504 -1.06272635 -0.47067559
   1.53002632  0.35088452 -0.51368238 -0.34340598]
 [ 0.03113688  0.85692477 -0.3463457   0.04962454  0.43279723  0.61942761
   1.34119208  0.41399672 -1.10827266  0.04472646]


In [79]:
# Print the mean, standard devietion of all numbers in M
print("Mean: ", np.mean(M))
print("Standard Deviation: ", np.std(M))


Mean:  -0.18015452116881409
Standard Deviation:  0.8716596458981362


In [80]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print("Max: ", np.max(M))
print("Third Quartile: ", np.percentile(M, 75))
print("Median: ", np.median(M))
print("First Quartile: ", np.percentile(M, 25))
print("Min: ", np.min(M))


Max:  2.1037226185492868
Third Quartile:  0.422717553570337
Median:  -0.10498242687613904
First Quartile:  -0.6632187508668068
Min:  -2.4228511306606513
